### ISSUE TITLE
"Bad ELF magic" exception on Android 

### ISSUE THREAD

**Issue by calm-rad** [staltz/sodium-native-nodejs-mobile#4]
This module works perfectly on iOS, but when I try to run my app on Android, I get this runtime error:

```
uncaughtException Error: dlopen failed: "/data/data/com.appname/files/nodejs-project/node_modules/sodium-native-nodejs-mobile/build/Release/sodium.node" has bad ELF magic: cffaedfe
        at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
        at Module.load (internal/modules/cjs/loader.js:598:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
        at Function.Module._load (internal/modules/cjs/loader.js:529:3)
        at Module.require (internal/modules/cjs/loader.js:636:17)
        at Object.apply (/data/data/com.appname/files/nodejs-project/main.js:17:20)
        at require (internal/modules/cjs/helpers.js:20:18)
        at /data/data/com.appname/files/nodejs-project/index.js:21:30
        at bindings (/data/data/com.appname/files/nodejs-project/index.js:723691:44)
        at Object.84wOzamum2jP+/5fIqg6RNZF+/nib1rh845LX3EpSg8= (/data/data/com.appname/files/nodejs-project/index.js:29180:33)
```

I suspect this has something to do with my Android build environment, but I'm not very familiar with Android. I tried to follow Manyverse's configuration as closely as possible, but I could be missing something. Any idea of where things might be going wrong?

**Comment by calm-rad** [comment]
Found the source of the issue! Turns out one of my build-backend scripts didn't delete the node_modules after the native modules were compiled, so nodejs-mobile was trying to use the wrong `.node` file.
