### ISSUE TITLE
Error: ./configure-mobile exited with 1

### ISSUE THREAD

**Issue by sylvaindesve** [staltz/sodium-native-nodejs-mobile#5]
Hi,

I'm trying to build and run [Manyverse](https://gitlab.com/staltz/manyverse) but `npm install` fails when building sodium-native-nodejs-mobile :

```
Error: Command failed: npm install --no-optional
/Users/sylvain.desve/Developer/community/manyverse/nodejs-assets/nodejs-project/node_modules/sodium-native-nodejs-mobile/preinstall.js:169
    if (err) throw err
             ^

Error: ./configure-mobile exited with 1
    at ChildProcess.<anonymous> (/Users/sylvain.desve/Developer/community/manyverse/nodejs-assets/nodejs-project/node_modules/sodium-native-nodejs-mobile/preinstall.js:213:25)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

Could it be because npm does not fetch the libsodium git submodule ?

**Comment by staltz** [comment]
Hi, just to make sure, have you rigorously followed all the instructions and software requirements (exact versions) described on https://gitlab.com/staltz/manyverse/-/blob/master/CONTRIBUTING.md ?

**Comment by sylvaindesve** [comment]
Blame me for overlooking this guide. I followed the instructions there and the error is slightly more specific now:

```
Error: ENOENT: no such file or directory, open '/Users/sylvain.desve/Developer/community/manyverse/nodejs-assets/nodejs-project/node_modules/sodium-native-nodejs-mobile/libsodium/libsodium-android-armv7-a/lib/libsodium.la'
```

**Comment by achou11** [comment]
I got this on MacOS because I had unliked the brew installed `libtool` at some point. Relinking seemed to solve the issue for me
