### ISSUE TITLE
sodium.node is wrong architecture for Android

### ISSUE THREAD

**Issue by RangerMauve** [staltz/sodium-native-nodejs-mobile#8]
I installed sodium-native-nodejs-mobile and got it to compile into the APK by cleaning out the `libsodium` folder.

However, when I try to require `sodium-native-nodejs-mobile` inside the nodejs-mobile project, I get the following stack trace:

```
10-13 16:03:38.486  9366  9453 E nodejs  : /data/data/com.teliosmobile/files/nodejs-project/node_modules/bindings/bindings.js:91
10-13 16:03:38.486  9366  9453 E nodejs  :         throw e
10-13 16:03:38.486  9366  9453 E nodejs  :         ^
10-13 16:03:38.486  9366  9453 E nodejs  : 
10-13 16:03:38.486  9366  9453 E nodejs  : Error: dlopen failed: "/data/data/com.teliosmobile/files/nodejs-project/node_modules/sodium-native-nodejs-mobile/build/Release/sodium.node" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1065:18)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Module.load (internal/modules/cjs/loader.js:879:32)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Module.require (internal/modules/cjs/loader.js:903:19)
10-13 16:03:38.486  9366  9453 E nodejs  :     at require (internal/modules/cjs/helpers.js:74:18)
10-13 16:03:38.486  9366  9453 E nodejs  :     at bindings (/data/data/com.teliosmobile/files/nodejs-project/node_modules/bindings/bindings.js:84:48)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Object.<anonymous> (/data/data/com.teliosmobile/files/nodejs-project/node_modules/sodium-native-nodejs-mobile/index.js:1:33)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Module._compile (internal/modules/cjs/loader.js:1015:30)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
10-13 16:03:38.486  9366  9453 E nodejs  :     at Module.load (internal/modules/cjs/loader.js:879:32)
```

As well, when I use `objdump` to inspect the sodium.node binary, I'm seeing the following:

```
objdump -f ./build/Release/sodium.node 

./build/Release/sodium.node:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x0000000000001040
```

This is telling me that it's not compiled for arm64, however I'm not seeing anything in the instructions or build scripts that would enable this functionality. 😅

I've tried stuff like specifying the architecture and platform for npm install, and that doesn't seem to help either. e.g. `npm i --save sodium-native-nodejs-mobile --target_arch=arm64 --target_platform=android`

I've also tried to rebuild with the `target_arch` argument, and the binary still seems to be x86-64. `node-gyp clean configure rebuild --verbose --target_arch=arm64`

What's strangeis that using target_arch=ia32 seems to compile the binary as expected.

```
node-gyp clean configure rebuild --verbose --target_arch=ia32

...

objdump -f ./build/Release/sodium.node 

./build/Release/sodium.node:     file format elf32-i386
architecture: i386, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00001050
```

Any pointers would be very much appreciated!

**Comment by RangerMauve** [comment]
Interesting. It seems like that Android compilation isn't invoking the code that does the nodejs-mobile-gyp code. :/ Have you seen this before?

Do I need to be running something other than `react-native run-android` to make it work? 😅

**Comment by RangerMauve** [comment]
It seems that my project properties didn't contain a `reactNativeDebugArchitectures` property, and this the abiFilters for the NDKI were null.

To fix it I added the `ndk.abiFilters` property to the defaultConfig in my `android/app/build.gradle`. (this was originally generated by react-native. You can see an example of this in manyverse' build here: https://gitlab.com/staltz/manyverse/-/blob/master/android/app/build.gradle#L159
